const MESSAGE = 'MESSAGE';
const ARCHIVEDMESSAGE = 'ARCHIVEDMESSAGE';
const GROUP = 'GROUP';
const STARREDMESSAGE = 'STARREDMESSAGE';
const SETTING = 'SETTING';
const LOGOUT = 'LOGOUT';
const CHATCONTENT = 'CHATCONTENT';

export {
  MESSAGE, ARCHIVEDMESSAGE, GROUP, STARREDMESSAGE, SETTING, LOGOUT, CHATCONTENT,
};
