import Head from 'next/head';
import React from 'react';
import MainMenu from '../components/organism/MainMenu';
import Chat from '../components/organism/Chat';
import ChatContent from '../components/organism/ChatContent';
import ContactInfo from '../components/organism/ContactInfo';

export default function Home() {
  return (
    <>
      <Head>
        <title>chattapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/490a850dc0.js" crossOrigin="anonymous" />
      </Head>
      <div className="container w-screen h-screen overflow-hidden flex">
        <section className="main__menu bg-slate-50 w-20 h-screen border-r-2">
          <MainMenu />
        </section>

        <section className="chat__preview w-96 h-screen border-r-2">
          <Chat />
        </section>

        <section className="chat__content w-6/12 h-screen border-r-2 relative">
          <ChatContent />
        </section>

        <section className="info flex-1">
          <ContactInfo />
        </section>
      </div>
    </>
  );
}
